kashtanproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tasks.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path('', views.index, name='index'),
    path('abort/', views.abort, name='abort'),
    path('excel/', views.excel, name='excel'),
    path('glossary/', views.glossary, name='glossary'),
    path('profile/', views.profile, name='profile'),
    path('tasks_argue/<int:task_id>/', views.tasks_argue, name='tasks_argue'),
    path('tasks_auto_check/', views.tasks_auto_check, name='auto_check'),
    path('tasks_verify/<int:task_id>/<int:price>/<int:user_id>', views.tasks_verify, name='tasks_verify'),
    path('variant/<int:pk>/', views.variant, name='variant')
]

tasks/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Task(models.Model):
    name = models.CharField(max_length=255)
    text_task = models.TextField()
    task_answer = models.CharField(max_length=255)
    sort_index = models.IntegerField(default=0)

    class Meta:
        ordering = ['sort_index']
        verbose_name_plural = 'Задания'
        verbose_name = 'Задание'

    def __str__(self):
        return f'{self.name}'


class Variant(models.Model):
    tasks = models.ManyToManyField(Task, related_name='tasks')

    class Meta:
        verbose_name_plural = 'Варианты'
        verbose_name = 'Вариант'

    def __str__(self):
        return f'Вариант {self.id}'


class UserTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='student')
    timestamp = models.DateTimeField(auto_now_add=True)
    answer = models.CharField(max_length=255, default="", null=True, blank=True)
    price = models.IntegerField(default=0)
    pricer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='teacher', default=None, null=True,
                               blank=True)
    # 0 - решил на проверку, 1 - проверено
    status = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Решенные задания'
        verbose_name = 'Решенное задание'

tasks/views.py
from datetime import datetime
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Border, Font, Side
from openpyxl.utils import get_column_letter

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from tasks.models import Variant, Task, UserTask


# Create your views here.

def index(request):
    variants = Variant.objects.all()
    return render(request, 'index.html', {'variants': variants})


def glossary(request):
    return render(request, 'glossary.html')


@login_required(login_url='/accounts/login/')
def profile(request):
    if request.user.is_superuser:
        group = "Администраторы"
    else:
        group = str(Group.objects.get(user=request.user))

    context_dict = {'group': group}

    if group == "Преподаватели" or group == "Администраторы":
        user_tasks = UserTask.objects.filter(status=0)
        context_dict['user_tasks'] = user_tasks

    if group == "Ученики":
        user_tasks = UserTask.objects.filter(user=request.user)
        context_dict['user_tasks'] = user_tasks

    return render(request, 'profile.html', context_dict)


@login_required(login_url='/accounts/login')
def variant(request, pk):
    if request.method == 'POST':
        d = {
            key: val if len(val) > 1 else val[0]
            for key, val in request.POST.lists()
        }
        z = list(zip(d.get('num_tasks[]'), d.get('tasks[]')))

        for task in z:
            t = Task.objects.get(pk=task[0])
            user_task = UserTask(task=t, user=request.user, answer=task[1])
            user_task.save()
        return render(request, 'variant_success.html')
    variant_obj = Variant.objects.get(pk=pk)
    tasks = variant_obj.tasks.all()
    return render(request, 'variant.html', {'variant': variant_obj, 'tasks': tasks})


@login_required(login_url='/accounts/login')
def tasks_verify(request, task_id, price, user_id):
    user_task = UserTask.objects.filter(task=task_id, user=user_id)
    user_task.update(price=price, status=True, pricer=request.user)
    return redirect('tasks:profile')


@login_required(login_url='/accounts/login')
def excel(request):
    # UserTasks оттуда взять всех юзеров с ГРУППИРОВКОЙ
    # потом надо на каждого юзера сделать ТУДА ЖЕ запрос и достать его оценки, сортировать по таскам
    # и в зависимости от таска выводить строчки, а потом уже ИТОГО и подпись
    data = []

    queryset = UserTask.objects.order_by().values('user').distinct()
    for task in queryset:
        real_task_list = [0] * 19
        task_list = list(UserTask.objects.filter(user=task['user']))
        task_list.sort(key=lambda x: x.task.sort_index, reverse=True)
        for i in range(len(task_list)):
            real_task_list[i] = task_list[i].price
        user = User.objects.get(pk=task['user'])

        data.append({
            'user': user.first_name + " " + user.last_name,
            'tasks': real_task_list
        })

    response = HttpResponse(content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    response['Content-Disposition'] = 'attachment; filename=report.xlsx'
    wb = load_workbook('report.xlsx')
    ws = wb['Лист1']
    ws.title = f'Отчет за {datetime.now().strftime("%Y-%m-%d")}'
    ft = Font(name='Times New Roman', size=12)
    brd = Border(left=Side(style='medium'), right=Side(style='medium'), top=Side(style='medium'),
                 bottom=Side(style='medium'))
    alg = Alignment(horizontal='center')

    row_num = 0
    student_num = 1
    columns = [
        ("№ п/п", 7),
        (u'Ученик', 30),
        ('№ 1', 5),
        ('№ 2', 5),
        ('№ 3', 5),
        ('№ 4', 5),
        ('№ 5', 5),
        ('№ 6', 5),
        ('№ 7', 5),
        ('№ 8', 5),
        ('№ 9', 5),
        ('№ 10', 5),
        ('№ 11', 5),
        ('№ 12', 5),
        ('№ 13', 5),
        ('№ 14', 5),
        ('№ 15', 5),
        ('№ 16', 5),
        ('№ 17', 5),
        ('№ 18', 5),
        ('№ 19', 5),
        ('Итого', 10)
    ]
    for col_num in range(len(columns)):
        c = ws.cell(row=row_num + 1, column=col_num + 1)
        c.font = ft
        c.border = brd
        c.alignment = alg
        c.value = columns[col_num][0]
        ws.column_dimensions[get_column_letter(col_num + 1)].width = columns[col_num][1]

    for data_row in data:
        row_num += 1
        row = [
            student_num,
            data_row.get('user'),
        ]
        row += data_row.get('tasks')
        row.append(f'=SUM(C{row_num + 1}:U{row_num + 1})')
        for col_num in range(len(row)):
            c = ws.cell(row=row_num + 1, column=col_num + 1)
            c.font = ft
            c.border = brd
            c.alignment = alg
            c.value = row[col_num]
        student_num += 1

    row_num += 3
    ws.merge_cells(f'T{row_num}:V{row_num}')

    c = ws.cell(row=row_num, column=20)
    c.font = ft
    c.alignment = Alignment(horizontal='right')
    c.value = datetime.now().strftime('%d.%m.%Y')

    c = ws.cell(row=row_num, column=2)
    c.font = ft
    c.value = request.user.first_name + " " + request.user.last_name

    wb.save(response)
    return response


@login_required(login_url='/accounts/login/')
def abort(request):
    UserTask.objects.all().delete()
    return redirect('tasks:profile')


@login_required(login_url='/accounts/login/')
def tasks_auto_check(request):
    tasks = UserTask.objects.filter(status=0)
    for task in tasks:
        if task.task.task_answer == task.answer:
            task_price = 1
        else:
            task_price = 0
        task.task_price = task_price
        task.status = True
        task.pricer = request.user
        task.save()
    return redirect('tasks:profile')


@login_required(login_url='/accounts/login/')
def tasks_argue(request, task_id):
    task = UserTask.objects.get(user_id=request.user.id, task_id=task_id)
    task.status = False
    task.save()
    return redirect('tasks:profile')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Подготовка к ОГЭ</title>
</head>
<body>

<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'tasks:index' %}"><i class="bi bi-house"></i>Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% with request.resolver_match.view_name as view_name %}
                        <li class="nav-item">
                            <a class="nav-link {% if view_name == "tasks:glossary" %}active{% endif %}"
                               aria-current="page" href="{% url 'tasks:glossary' %}">
                                <i class="bi bi-book"></i>База знаний
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if view_name == "tasks:profile" %}active{% endif %}"
                               href="{% url 'tasks:profile' %}"><i class="bi bi-card-list"></i>Мой профиль</a>
                        </li>
                    {% endwith %}
                </ul>
            </div>
            <div class="d-flex align-items-center">
                {% if user.username %}
                    {{ user }}
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button title="Выход" type="submit"
                                class="border-0 bg-transparent text-primary text-decoration-underline">
                            <i class="bi bi-box-arrow-in-right"></i>
                        </button>
                    </form>
                {% else %}
                <span>Для доступа к профилю &nbsp;</span>
                <a href="{% url 'login' %}"><button type="button" class="btn btn-primary">Войдите в систему</button> </a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% block content %}{% endblock %}

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top text-light">
        <div class="col-md-4 d-flex align-items-center">
            <span class="mb-3 mb-md-0">© 2024 Mukashev Corp.</span>
        </div>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="px-4 py-5 my-5 text-center text-light">
    <div class="card m-auto w-50">
        <img src="{% static 'img\picture2.jpg' %}" class="card-img-top" alt="...">
      </div>
    <h1 class="display-5 fw-bold">Добро пожаловать</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Данный сайт был разработан с целью обеспечения подготовки учеников к ОГЭ по
            математике.</p>
    </div>
</div>



    <h1 class="text-light">Тренировочные варианты</h1>

    <div class="row my-4">
        {% for variant in variants %}
            <div class="col-2 text-center">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Вариант {{ forloop.counter }}</h5>
                        <a href="{% url 'tasks:variant' pk=variant.id %}"
                           class="btn btn-outline-success">Приступить</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if user.is_superuser %}
        <a href="/admin" class="link-info text-decoration-none row col-2 m-auto">Панель администратора</a>
    {% endif %}
    {% if user.username %}
        <div class="row my-4">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Информация о пользователе</h5>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">
                                <img class="card-img" src="{% static 'img/profile.png' %}">
                            </div>
                            <div class="col-6">
                                <ul class="list-group">
                                    <li class="list-group-item">Имя: {{ user.first_name }}</li>
                                    <li class="list-group-item">Фамилия: {{ user.last_name }}</li>
                                    <li class="list-group-item">Email: {{ user.email }}</li>
                                    <li class="list-group-item">Группа: {{ group }}</li>
                                    {% if group == "Преподаватели" or group == "Администраторы" %}
                                        <li class="list-group-item">
                                            <div class="btn-group d-flex">
                                                <a href="{% url 'tasks:excel' %}" class="btn btn-success">Отчет в
                                                    Excel</a>
                                                <a href="{% url 'tasks:abort' %}" class="btn btn-danger">Сброс</a>
                                            </div>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    {% if group == "Преподаватели" or group == "Администраторы" %}
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <h5 class="card-title">Задания на проверку</h5>
                            <a href="{% url 'tasks:auto_check' %}" class="btn btn-warning">Автопроверка</a>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                {% for user_task in user_tasks %}
                                    <div class="col-12"><h5 class="card-title">Задание № {{ user_task.task_id }}</h5>
                                    </div>
                                    <div class="col-6">
                                        <p class="card-text">Текст задания:</p>
                                        <pre>{% autoescape off %}{{ user_task.task.text_task }}{% endautoescape %}</pre>
                                    </div>
                                    <div class="col-6">
                                        <p class="card-text">Решил: {{ user_task.user.first_name }} {{ user_task.user.last_name }}</p>
                                        <p class="card-text">Ответ: {{ user_task.answer }}</p>
                                    </div>
                                    <div class="col-6"><p class="card-text">Оценка: </p></div>
                                    <div class="col-12 btn-group mb-4">
                                        <a href="{% url 'tasks:tasks_verify' task_id=user_task.task.id price=0 user_id=user_task.user.id %}"
                                           class="btn btn-danger">0</a>
                                        <a href="{% url 'tasks:tasks_verify' task_id=user_task.task.id price=1 user_id=user_task.user.id %}"
                                           class="btn btn-success">1</a>
                                    </div>
                                    <hr>
                                {% endfor %}
                            </div>
                        </div>
                    {% else %}
                        <div class="card-header">
                            <h5 class="card-title">Выполненные задачи</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                {% for user_task in user_tasks %}
                                    <div class="col-12 d-flex justify-content-between">
                                        <h4>Задание {{ user_task.task.id }}</h4>
                                        {% if user_task.status %}
                                            <a href="{% url 'tasks:tasks_argue' task_id=user_task.task.id %}"
                                               class="btn btn-warning">Оспорить</a>
                                        {% endif %}
                                    </div>
                                    <div class="col-6">
                                        <p class="card-text">Текст задания:</p>
                                        <pre>{% autoescape off %}{{ user_task.task.text_task }}{% endautoescape %}</pre>
                                        <p class="card-text">Ваш ответ: {{ user_task.answer }}</p>
                                        <p class="card-text">Правильный ответ: {{ user_task.task.task_answer }}</p>
                                    </div>
                                    <div class="col-6">
                                        {% if user_task.status %}
                                            <p class="card-text">Статус: Проверено</p>
                                            <p class="card-text">Оценка: {{ user_task.price }}</p>
                                            <p class="card-text">Проверил: {{ user_task.pricer.first_name }} {{ user_task.pricer.last_name }}</p>
                                        {% else %}
                                            <p class="card-text">Статус: На проверке</p>
                                        {% endif %}
                                    </div>
                                    <hr>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

    {% endif %}
{% endblock %}

templates/tasks.html
{% extends 'base.html' %}

{% block content %}
    <div class="row my-4">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <nav class="h-100 flex-column align-items-stretch pe-4 border-end">
                        <nav class="nav nav-pills flex-column">
                            {% for type_group, type_tasks in type_groups.items %}
                                <a class="nav-link {% if filter_type_group == type_group.id %}active{% endif %}" href="
                                        {% url 'tasks:tasks' filter_type_group=type_group.id %}">{{ forloop.counter }}.{{ type_group }}
                                </a>
                                <nav class="nav nav-pills flex-column">
                                    {% for type_task in type_tasks %}
                                        <a class="nav-link {% if filter_type_task == type_task.id %}active{% endif %} ms-3 my-1"
                                           href="{% url 'tasks:tasks' filter_type_task=type_task.id %}">
                                            {{ forloop.parentloop.counter }}.{{ forloop.counter }} {{ type_task }}
                                        </a>
                                    {% endfor %}
                                </nav>
                            {% endfor %}
                        </nav>
                    </nav>

                </div>
            </div>

        </div>
        <div class="col-6">
            <div class="card card-body">
                {% if active_tasks %}
                    {% for task in active_tasks %}
                        <p class="d-inline-flex gap-1">
                        <h5>Задание: {{ task.name }}</h5>
                        <pre>{{ task.text_task }}</pre>
                        <a class="btn btn-primary" data-bs-toggle="collapse"
                           href="#collapseExample{{ forloop.counter }}" role="button"
                           aria-expanded="false" aria-controls="collapseExample">
                            Решение
                        </a>
                        </p>
                        <div class="collapse" id="collapseExample{{ forloop.counter }}">
                            <div class="card card-body">
                                <pre>{{ task.text_solution }}</pre>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h5 class="card-title">Выберите тип задач</h5>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/variant.html
{% extends 'base.html' %}

{% block content %}
    <h5 class="text-light text-center">{{ variant }}</h5>
    <form action="{% url 'tasks:variant' pk=variant.id %}" method="post">
        {% csrf_token %}
        {% for task in tasks %}
            <div class="card mb-4">
                <div class="card-header">
                    <h5 class="card-title">Задача {{ forloop.counter }}</h5>
                </div>
                <div class="card-body">
                    <input type="hidden" name="num_tasks[]" value="{{ task.id }}">
                    {% autoescape off %}
                        <p class="card-text">{{ task.text_task }}</p>
                    {% endautoescape %}
                <hr>
                    <label for="task_{{ forloop.counter }}" class="form-label">Ваш ответ</label>
                    <input id="task_{{ forloop.counter }}" class="form-control" type="text" name="tasks[]">
                </div>
            </div>
        {% endfor %}
        <div class="text-center">
            <button type="submit" class="btn btn-success">Отправить решения</button>
        </div>
    </form>
    <p class="text-light text-center">Задания второй части будут проверяться учителем отдельно</p>
{% endblock %}

templates/variant_success.html
{% extends 'base.html' %}


{% block content %}
    <h1 class="text-light text-center">Вы успешно отправили свои решения. Дождитесь, пока учитель проверит ваши ответы.</h1>
{% endblock %}